// Copyright 2022 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "antrea.io/antrea/pkg/apis/crd/v1alpha1"
	scheme "antrea.io/antrea/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// L7NetworkPoliciesGetter has a method to return a L7NetworkPolicyInterface.
// A group's client should implement this interface.
type L7NetworkPoliciesGetter interface {
	L7NetworkPolicies(namespace string) L7NetworkPolicyInterface
}

// L7NetworkPolicyInterface has methods to work with L7NetworkPolicy resources.
type L7NetworkPolicyInterface interface {
	Create(ctx context.Context, l7NetworkPolicy *v1alpha1.L7NetworkPolicy, opts v1.CreateOptions) (*v1alpha1.L7NetworkPolicy, error)
	Update(ctx context.Context, l7NetworkPolicy *v1alpha1.L7NetworkPolicy, opts v1.UpdateOptions) (*v1alpha1.L7NetworkPolicy, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.L7NetworkPolicy, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.L7NetworkPolicyList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.L7NetworkPolicy, err error)
	L7NetworkPolicyExpansion
}

// l7NetworkPolicies implements L7NetworkPolicyInterface
type l7NetworkPolicies struct {
	client rest.Interface
	ns     string
}

// newL7NetworkPolicies returns a L7NetworkPolicies
func newL7NetworkPolicies(c *CrdV1alpha1Client, namespace string) *l7NetworkPolicies {
	return &l7NetworkPolicies{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the l7NetworkPolicy, and returns the corresponding l7NetworkPolicy object, and an error if there is any.
func (c *l7NetworkPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.L7NetworkPolicy, err error) {
	result = &v1alpha1.L7NetworkPolicy{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("l7networkpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of L7NetworkPolicies that match those selectors.
func (c *l7NetworkPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.L7NetworkPolicyList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.L7NetworkPolicyList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("l7networkpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested l7NetworkPolicies.
func (c *l7NetworkPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("l7networkpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a l7NetworkPolicy and creates it.  Returns the server's representation of the l7NetworkPolicy, and an error, if there is any.
func (c *l7NetworkPolicies) Create(ctx context.Context, l7NetworkPolicy *v1alpha1.L7NetworkPolicy, opts v1.CreateOptions) (result *v1alpha1.L7NetworkPolicy, err error) {
	result = &v1alpha1.L7NetworkPolicy{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("l7networkpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(l7NetworkPolicy).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a l7NetworkPolicy and updates it. Returns the server's representation of the l7NetworkPolicy, and an error, if there is any.
func (c *l7NetworkPolicies) Update(ctx context.Context, l7NetworkPolicy *v1alpha1.L7NetworkPolicy, opts v1.UpdateOptions) (result *v1alpha1.L7NetworkPolicy, err error) {
	result = &v1alpha1.L7NetworkPolicy{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("l7networkpolicies").
		Name(l7NetworkPolicy.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(l7NetworkPolicy).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the l7NetworkPolicy and deletes it. Returns an error if one occurs.
func (c *l7NetworkPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("l7networkpolicies").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *l7NetworkPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("l7networkpolicies").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched l7NetworkPolicy.
func (c *l7NetworkPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.L7NetworkPolicy, err error) {
	result = &v1alpha1.L7NetworkPolicy{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("l7networkpolicies").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
