// Copyright 2020 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/vmware-tanzu/antrea/pkg/apis/crd/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTierEntitlementBindings implements TierEntitlementBindingInterface
type FakeTierEntitlementBindings struct {
	Fake *FakeCrdV1alpha1
}

var tierentitlementbindingsResource = schema.GroupVersionResource{Group: "crd.antrea.tanzu.vmware.com", Version: "v1alpha1", Resource: "tierentitlementbindings"}

var tierentitlementbindingsKind = schema.GroupVersionKind{Group: "crd.antrea.tanzu.vmware.com", Version: "v1alpha1", Kind: "TierEntitlementBinding"}

// Get takes name of the tierEntitlementBinding, and returns the corresponding tierEntitlementBinding object, and an error if there is any.
func (c *FakeTierEntitlementBindings) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TierEntitlementBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(tierentitlementbindingsResource, name), &v1alpha1.TierEntitlementBinding{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TierEntitlementBinding), err
}

// List takes label and field selectors, and returns the list of TierEntitlementBindings that match those selectors.
func (c *FakeTierEntitlementBindings) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TierEntitlementBindingList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(tierentitlementbindingsResource, tierentitlementbindingsKind, opts), &v1alpha1.TierEntitlementBindingList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TierEntitlementBindingList{ListMeta: obj.(*v1alpha1.TierEntitlementBindingList).ListMeta}
	for _, item := range obj.(*v1alpha1.TierEntitlementBindingList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested tierEntitlementBindings.
func (c *FakeTierEntitlementBindings) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(tierentitlementbindingsResource, opts))
}

// Create takes the representation of a tierEntitlementBinding and creates it.  Returns the server's representation of the tierEntitlementBinding, and an error, if there is any.
func (c *FakeTierEntitlementBindings) Create(ctx context.Context, tierEntitlementBinding *v1alpha1.TierEntitlementBinding, opts v1.CreateOptions) (result *v1alpha1.TierEntitlementBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(tierentitlementbindingsResource, tierEntitlementBinding), &v1alpha1.TierEntitlementBinding{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TierEntitlementBinding), err
}

// Update takes the representation of a tierEntitlementBinding and updates it. Returns the server's representation of the tierEntitlementBinding, and an error, if there is any.
func (c *FakeTierEntitlementBindings) Update(ctx context.Context, tierEntitlementBinding *v1alpha1.TierEntitlementBinding, opts v1.UpdateOptions) (result *v1alpha1.TierEntitlementBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(tierentitlementbindingsResource, tierEntitlementBinding), &v1alpha1.TierEntitlementBinding{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TierEntitlementBinding), err
}

// Delete takes name of the tierEntitlementBinding and deletes it. Returns an error if one occurs.
func (c *FakeTierEntitlementBindings) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(tierentitlementbindingsResource, name), &v1alpha1.TierEntitlementBinding{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTierEntitlementBindings) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(tierentitlementbindingsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TierEntitlementBindingList{})
	return err
}

// Patch applies the patch and returns the patched tierEntitlementBinding.
func (c *FakeTierEntitlementBindings) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TierEntitlementBinding, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(tierentitlementbindingsResource, name, pt, data, subresources...), &v1alpha1.TierEntitlementBinding{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TierEntitlementBinding), err
}
