// Copyright 2022 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "antrea.io/antrea/pkg/apis/crd/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeL7NetworkPolicies implements L7NetworkPolicyInterface
type FakeL7NetworkPolicies struct {
	Fake *FakeCrdV1alpha1
	ns   string
}

var l7networkpoliciesResource = schema.GroupVersionResource{Group: "crd.antrea.io", Version: "v1alpha1", Resource: "l7networkpolicies"}

var l7networkpoliciesKind = schema.GroupVersionKind{Group: "crd.antrea.io", Version: "v1alpha1", Kind: "L7NetworkPolicy"}

// Get takes name of the l7NetworkPolicy, and returns the corresponding l7NetworkPolicy object, and an error if there is any.
func (c *FakeL7NetworkPolicies) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.L7NetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(l7networkpoliciesResource, c.ns, name), &v1alpha1.L7NetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.L7NetworkPolicy), err
}

// List takes label and field selectors, and returns the list of L7NetworkPolicies that match those selectors.
func (c *FakeL7NetworkPolicies) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.L7NetworkPolicyList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(l7networkpoliciesResource, l7networkpoliciesKind, c.ns, opts), &v1alpha1.L7NetworkPolicyList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.L7NetworkPolicyList{ListMeta: obj.(*v1alpha1.L7NetworkPolicyList).ListMeta}
	for _, item := range obj.(*v1alpha1.L7NetworkPolicyList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested l7NetworkPolicies.
func (c *FakeL7NetworkPolicies) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(l7networkpoliciesResource, c.ns, opts))

}

// Create takes the representation of a l7NetworkPolicy and creates it.  Returns the server's representation of the l7NetworkPolicy, and an error, if there is any.
func (c *FakeL7NetworkPolicies) Create(ctx context.Context, l7NetworkPolicy *v1alpha1.L7NetworkPolicy, opts v1.CreateOptions) (result *v1alpha1.L7NetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(l7networkpoliciesResource, c.ns, l7NetworkPolicy), &v1alpha1.L7NetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.L7NetworkPolicy), err
}

// Update takes the representation of a l7NetworkPolicy and updates it. Returns the server's representation of the l7NetworkPolicy, and an error, if there is any.
func (c *FakeL7NetworkPolicies) Update(ctx context.Context, l7NetworkPolicy *v1alpha1.L7NetworkPolicy, opts v1.UpdateOptions) (result *v1alpha1.L7NetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(l7networkpoliciesResource, c.ns, l7NetworkPolicy), &v1alpha1.L7NetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.L7NetworkPolicy), err
}

// Delete takes name of the l7NetworkPolicy and deletes it. Returns an error if one occurs.
func (c *FakeL7NetworkPolicies) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(l7networkpoliciesResource, c.ns, name, opts), &v1alpha1.L7NetworkPolicy{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeL7NetworkPolicies) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(l7networkpoliciesResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.L7NetworkPolicyList{})
	return err
}

// Patch applies the patch and returns the patched l7NetworkPolicy.
func (c *FakeL7NetworkPolicies) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.L7NetworkPolicy, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(l7networkpoliciesResource, c.ns, name, pt, data, subresources...), &v1alpha1.L7NetworkPolicy{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.L7NetworkPolicy), err
}
