// Copyright 2021 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "antrea.io/antrea/pkg/apis/crd/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeTrafficControlConfigurations implements TrafficControlConfigurationInterface
type FakeTrafficControlConfigurations struct {
	Fake *FakeCrdV1alpha1
}

var trafficcontrolconfigurationsResource = schema.GroupVersionResource{Group: "crd.antrea.io", Version: "v1alpha1", Resource: "trafficcontrolconfigurations"}

var trafficcontrolconfigurationsKind = schema.GroupVersionKind{Group: "crd.antrea.io", Version: "v1alpha1", Kind: "TrafficControlConfiguration"}

// Get takes name of the trafficControlConfiguration, and returns the corresponding trafficControlConfiguration object, and an error if there is any.
func (c *FakeTrafficControlConfigurations) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.TrafficControlConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(trafficcontrolconfigurationsResource, name), &v1alpha1.TrafficControlConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficControlConfiguration), err
}

// List takes label and field selectors, and returns the list of TrafficControlConfigurations that match those selectors.
func (c *FakeTrafficControlConfigurations) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.TrafficControlConfigurationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(trafficcontrolconfigurationsResource, trafficcontrolconfigurationsKind, opts), &v1alpha1.TrafficControlConfigurationList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.TrafficControlConfigurationList{ListMeta: obj.(*v1alpha1.TrafficControlConfigurationList).ListMeta}
	for _, item := range obj.(*v1alpha1.TrafficControlConfigurationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested trafficControlConfigurations.
func (c *FakeTrafficControlConfigurations) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(trafficcontrolconfigurationsResource, opts))
}

// Create takes the representation of a trafficControlConfiguration and creates it.  Returns the server's representation of the trafficControlConfiguration, and an error, if there is any.
func (c *FakeTrafficControlConfigurations) Create(ctx context.Context, trafficControlConfiguration *v1alpha1.TrafficControlConfiguration, opts v1.CreateOptions) (result *v1alpha1.TrafficControlConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(trafficcontrolconfigurationsResource, trafficControlConfiguration), &v1alpha1.TrafficControlConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficControlConfiguration), err
}

// Update takes the representation of a trafficControlConfiguration and updates it. Returns the server's representation of the trafficControlConfiguration, and an error, if there is any.
func (c *FakeTrafficControlConfigurations) Update(ctx context.Context, trafficControlConfiguration *v1alpha1.TrafficControlConfiguration, opts v1.UpdateOptions) (result *v1alpha1.TrafficControlConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(trafficcontrolconfigurationsResource, trafficControlConfiguration), &v1alpha1.TrafficControlConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficControlConfiguration), err
}

// Delete takes name of the trafficControlConfiguration and deletes it. Returns an error if one occurs.
func (c *FakeTrafficControlConfigurations) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(trafficcontrolconfigurationsResource, name), &v1alpha1.TrafficControlConfiguration{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeTrafficControlConfigurations) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(trafficcontrolconfigurationsResource, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.TrafficControlConfigurationList{})
	return err
}

// Patch applies the patch and returns the patched trafficControlConfiguration.
func (c *FakeTrafficControlConfigurations) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.TrafficControlConfiguration, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(trafficcontrolconfigurationsResource, name, pt, data, subresources...), &v1alpha1.TrafficControlConfiguration{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.TrafficControlConfiguration), err
}
