// Copyright 2020 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/vmware-tanzu/antrea/pkg/apis/controlplane/v1alpha1/generated.proto

package v1alpha1

import (
	fmt "fmt"

	io "io"

	proto "github.com/gogo/protobuf/proto"

	math "math"
	math_bits "math/bits"
	reflect "reflect"
	strings "strings"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

func (m *NetworkPolicyReference) Reset()      { *m = NetworkPolicyReference{} }
func (*NetworkPolicyReference) ProtoMessage() {}
func (*NetworkPolicyReference) Descriptor() ([]byte, []int) {
	return fileDescriptor_846b555039d6cceb, []int{0}
}
func (m *NetworkPolicyReference) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NetworkPolicyReference) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NetworkPolicyReference) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkPolicyReference.Merge(m, src)
}
func (m *NetworkPolicyReference) XXX_Size() int {
	return m.Size()
}
func (m *NetworkPolicyReference) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkPolicyReference.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkPolicyReference proto.InternalMessageInfo

func (m *NetworkPolicyStats) Reset()      { *m = NetworkPolicyStats{} }
func (*NetworkPolicyStats) ProtoMessage() {}
func (*NetworkPolicyStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_846b555039d6cceb, []int{1}
}
func (m *NetworkPolicyStats) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NetworkPolicyStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NetworkPolicyStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NetworkPolicyStats.Merge(m, src)
}
func (m *NetworkPolicyStats) XXX_Size() int {
	return m.Size()
}
func (m *NetworkPolicyStats) XXX_DiscardUnknown() {
	xxx_messageInfo_NetworkPolicyStats.DiscardUnknown(m)
}

var xxx_messageInfo_NetworkPolicyStats proto.InternalMessageInfo

func (m *NodeStatsSummary) Reset()      { *m = NodeStatsSummary{} }
func (*NodeStatsSummary) ProtoMessage() {}
func (*NodeStatsSummary) Descriptor() ([]byte, []int) {
	return fileDescriptor_846b555039d6cceb, []int{2}
}
func (m *NodeStatsSummary) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *NodeStatsSummary) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}
func (m *NodeStatsSummary) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NodeStatsSummary.Merge(m, src)
}
func (m *NodeStatsSummary) XXX_Size() int {
	return m.Size()
}
func (m *NodeStatsSummary) XXX_DiscardUnknown() {
	xxx_messageInfo_NodeStatsSummary.DiscardUnknown(m)
}

var xxx_messageInfo_NodeStatsSummary proto.InternalMessageInfo

func init() {
	proto.RegisterType((*NetworkPolicyReference)(nil), "github.com.vmware_tanzu.antrea.pkg.apis.controlplane.v1alpha1.NetworkPolicyReference")
	proto.RegisterType((*NetworkPolicyStats)(nil), "github.com.vmware_tanzu.antrea.pkg.apis.controlplane.v1alpha1.NetworkPolicyStats")
	proto.RegisterType((*NodeStatsSummary)(nil), "github.com.vmware_tanzu.antrea.pkg.apis.controlplane.v1alpha1.NodeStatsSummary")
}

func init() {
	proto.RegisterFile("github.com/vmware-tanzu/antrea/pkg/apis/controlplane/v1alpha1/generated.proto", fileDescriptor_846b555039d6cceb)
}

var fileDescriptor_846b555039d6cceb = []byte{
	// 531 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x92, 0x3f, 0x6f, 0xd3, 0x4e,
	0x18, 0xc7, 0x73, 0x69, 0x87, 0xe4, 0x92, 0xaa, 0xbf, 0x9f, 0x45, 0x21, 0xca, 0xe0, 0x54, 0x99,
	0xca, 0xd0, 0x3b, 0x12, 0x21, 0xc4, 0xc2, 0x12, 0x04, 0x62, 0x69, 0x00, 0x17, 0x16, 0x16, 0x78,
	0x72, 0x79, 0xe2, 0x98, 0xc4, 0x3e, 0xeb, 0x7c, 0x49, 0x15, 0xa6, 0xee, 0x2c, 0x08, 0xf1, 0x32,
	0x98, 0x78, 0x15, 0x19, 0x3b, 0x76, 0x8a, 0x88, 0x79, 0x17, 0x4c, 0xc8, 0x17, 0xa7, 0xb1, 0x5b,
	0x2a, 0x2a, 0xc1, 0xe6, 0xe7, 0xcf, 0xf7, 0xfb, 0x7c, 0xfc, 0xdc, 0x43, 0x8f, 0x5c, 0x4f, 0x0f,
	0x27, 0x3d, 0x26, 0xa4, 0xcf, 0xa7, 0xfe, 0x09, 0x28, 0x3c, 0xd4, 0x10, 0x7c, 0x98, 0x70, 0x08,
	0xb4, 0x42, 0xe0, 0xe1, 0xc8, 0xe5, 0x10, 0x7a, 0x11, 0x17, 0x32, 0xd0, 0x4a, 0x8e, 0xc3, 0x31,
	0x04, 0xc8, 0xa7, 0x2d, 0x18, 0x87, 0x43, 0x68, 0x71, 0x17, 0x03, 0x54, 0xa0, 0xb1, 0xcf, 0x42,
	0x25, 0xb5, 0xb4, 0x1e, 0x6d, 0xec, 0xd8, 0xca, 0xee, 0xad, 0xb1, 0x63, 0x2b, 0x3b, 0x16, 0x8e,
	0x5c, 0x96, 0xd8, 0xb1, 0xac, 0x1d, 0x5b, 0xdb, 0xd5, 0x0f, 0x33, 0x34, 0xae, 0x74, 0x25, 0x37,
	0xae, 0xbd, 0xc9, 0xc0, 0x44, 0x26, 0x30, 0x5f, 0xab, 0x69, 0xf5, 0x67, 0x37, 0x85, 0xf7, 0x51,
	0x2b, 0x4f, 0x44, 0xd7, 0x72, 0xd7, 0xef, 0x8f, 0x1e, 0x46, 0xcc, 0x93, 0x49, 0xb7, 0x0f, 0x62,
	0xe8, 0x05, 0xa8, 0x66, 0x39, 0x39, 0xf0, 0xe9, 0x55, 0x15, 0xbf, 0x4e, 0xa5, 0x26, 0x81, 0xf6,
	0x7c, 0xbc, 0x22, 0x78, 0xf0, 0x27, 0x41, 0x24, 0x86, 0xe8, 0xc3, 0x65, 0x5d, 0xf3, 0x1b, 0xa1,
	0xb7, 0xbb, 0xa8, 0x4f, 0xa4, 0x1a, 0xbd, 0x90, 0x63, 0x4f, 0xcc, 0x1c, 0x1c, 0xa0, 0xc2, 0x40,
	0xa0, 0xf5, 0x84, 0x96, 0x04, 0x68, 0x74, 0xa5, 0x9a, 0xd5, 0xc8, 0x3e, 0x39, 0x28, 0x77, 0xee,
	0xce, 0x17, 0x8d, 0x42, 0xbc, 0x68, 0x94, 0x1e, 0xa7, 0xf9, 0x9f, 0x8b, 0xc6, 0x5e, 0x4e, 0xbd,
	0x2e, 0x38, 0x17, 0x52, 0x8b, 0xd3, 0x72, 0x00, 0x3e, 0x46, 0x21, 0x08, 0xac, 0x15, 0x8d, 0xcf,
	0xff, 0xa9, 0x4f, 0xb9, 0xbb, 0x2e, 0x38, 0x9b, 0x1e, 0x6b, 0x9f, 0x6e, 0x27, 0x41, 0x6d, 0xcb,
	0xf4, 0x56, 0xd3, 0xde, 0xed, 0xa4, 0xd7, 0x31, 0x95, 0xe6, 0xd7, 0x22, 0xb5, 0x72, 0x63, 0x8f,
	0x35, 0xe8, 0xc8, 0xfa, 0x4c, 0xe8, 0x4e, 0x90, 0x4d, 0x1b, 0xec, 0x4a, 0xfb, 0x35, 0xfb, 0xab,
	0xdb, 0x61, 0xbf, 0xdf, 0x4f, 0x67, 0x2f, 0x25, 0xdb, 0xc9, 0xd7, 0xf3, 0x08, 0xd6, 0x29, 0xa1,
	0x55, 0xad, 0x60, 0x30, 0xf0, 0x84, 0xa1, 0x34, 0x2b, 0xa8, 0xb4, 0x9f, 0xde, 0x98, 0x29, 0xbd,
	0xb0, 0x0d, 0xce, 0xab, 0x8c, 0x5b, 0xe7, 0x56, 0x0a, 0x51, 0xcd, 0x66, 0x9d, 0xdc, 0xc4, 0xe6,
	0xc7, 0x22, 0xfd, 0xaf, 0x2b, 0xfb, 0x68, 0xa2, 0xe3, 0x89, 0xef, 0x83, 0x9a, 0x59, 0xef, 0x68,
	0x29, 0x39, 0xbe, 0x3e, 0x68, 0x48, 0xd7, 0x74, 0x8f, 0xad, 0x6e, 0x88, 0x65, 0x6f, 0x28, 0xc7,
	0x01, 0x6c, 0xda, 0x62, 0xcf, 0x7b, 0xef, 0x51, 0xe8, 0x23, 0xd4, 0xd0, 0xb1, 0xd2, 0xe1, 0x74,
	0x93, 0x73, 0x2e, 0x5c, 0xad, 0x2f, 0x84, 0xee, 0x66, 0x77, 0xe1, 0x61, 0xf2, 0xf3, 0x5b, 0x07,
	0x95, 0xf6, 0xcb, 0x7f, 0xf9, 0x20, 0xab, 0x3d, 0xdc, 0x49, 0x51, 0x76, 0xbb, 0xf9, 0x89, 0xce,
	0x65, 0x84, 0x0e, 0x9b, 0x2f, 0xed, 0xc2, 0xd9, 0xd2, 0x2e, 0x9c, 0x2f, 0xed, 0xc2, 0x69, 0x6c,
	0x93, 0x79, 0x6c, 0x93, 0xb3, 0xd8, 0x26, 0xe7, 0xb1, 0x4d, 0xbe, 0xc7, 0x36, 0xf9, 0xf4, 0xc3,
	0x2e, 0xbc, 0x29, 0xad, 0x87, 0xfd, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x3f, 0x50, 0x28, 0x5f, 0xc8,
	0x04, 0x00, 0x00,
}

func (m *NetworkPolicyReference) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetworkPolicyReference) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NetworkPolicyReference) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	i -= len(m.Name)
	copy(dAtA[i:], m.Name)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Name)))
	i--
	dAtA[i] = 0x1a
	i -= len(m.Namespace)
	copy(dAtA[i:], m.Namespace)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Namespace)))
	i--
	dAtA[i] = 0x12
	i -= len(m.Category)
	copy(dAtA[i:], m.Category)
	i = encodeVarintGenerated(dAtA, i, uint64(len(m.Category)))
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *NetworkPolicyStats) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NetworkPolicyStats) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NetworkPolicyStats) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TrafficStats.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size, err := m.NetworkPolicy.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *NodeStatsSummary) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *NodeStatsSummary) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *NodeStatsSummary) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.NetworkPolicies) > 0 {
		for iNdEx := len(m.NetworkPolicies) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.NetworkPolicies[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintGenerated(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.ObjectMeta.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintGenerated(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func encodeVarintGenerated(dAtA []byte, offset int, v uint64) int {
	offset -= sovGenerated(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *NetworkPolicyReference) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Category)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Namespace)
	n += 1 + l + sovGenerated(uint64(l))
	l = len(m.Name)
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *NetworkPolicyStats) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.NetworkPolicy.Size()
	n += 1 + l + sovGenerated(uint64(l))
	l = m.TrafficStats.Size()
	n += 1 + l + sovGenerated(uint64(l))
	return n
}

func (m *NodeStatsSummary) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.ObjectMeta.Size()
	n += 1 + l + sovGenerated(uint64(l))
	if len(m.NetworkPolicies) > 0 {
		for _, e := range m.NetworkPolicies {
			l = e.Size()
			n += 1 + l + sovGenerated(uint64(l))
		}
	}
	return n
}

func sovGenerated(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozGenerated(x uint64) (n int) {
	return sovGenerated(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *NetworkPolicyReference) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&NetworkPolicyReference{`,
		`Category:` + fmt.Sprintf("%v", this.Category) + `,`,
		`Namespace:` + fmt.Sprintf("%v", this.Namespace) + `,`,
		`Name:` + fmt.Sprintf("%v", this.Name) + `,`,
		`}`,
	}, "")
	return s
}
func (this *NetworkPolicyStats) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&NetworkPolicyStats{`,
		`NetworkPolicy:` + strings.Replace(strings.Replace(this.NetworkPolicy.String(), "NetworkPolicyReference", "NetworkPolicyReference", 1), `&`, ``, 1) + `,`,
		`TrafficStats:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.TrafficStats), "TrafficStats", "v1alpha1.TrafficStats", 1), `&`, ``, 1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *NodeStatsSummary) String() string {
	if this == nil {
		return "nil"
	}
	repeatedStringForNetworkPolicies := "[]NetworkPolicyStats{"
	for _, f := range this.NetworkPolicies {
		repeatedStringForNetworkPolicies += strings.Replace(strings.Replace(f.String(), "NetworkPolicyStats", "NetworkPolicyStats", 1), `&`, ``, 1) + ","
	}
	repeatedStringForNetworkPolicies += "}"
	s := strings.Join([]string{`&NodeStatsSummary{`,
		`ObjectMeta:` + strings.Replace(strings.Replace(fmt.Sprintf("%v", this.ObjectMeta), "ObjectMeta", "v1.ObjectMeta", 1), `&`, ``, 1) + `,`,
		`NetworkPolicies:` + repeatedStringForNetworkPolicies + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringGenerated(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *NetworkPolicyReference) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetworkPolicyReference: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetworkPolicyReference: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Category", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Category = NetworkPolicyCategory(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Namespace", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Namespace = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Name", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NetworkPolicyStats) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NetworkPolicyStats: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NetworkPolicyStats: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkPolicy", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.NetworkPolicy.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TrafficStats", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TrafficStats.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *NodeStatsSummary) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: NodeStatsSummary: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: NodeStatsSummary: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ObjectMeta", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ObjectMeta.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field NetworkPolicies", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthGenerated
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthGenerated
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.NetworkPolicies = append(m.NetworkPolicies, NetworkPolicyStats{})
			if err := m.NetworkPolicies[len(m.NetworkPolicies)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipGenerated(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) < 0 {
				return ErrInvalidLengthGenerated
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipGenerated(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowGenerated
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowGenerated
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthGenerated
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupGenerated
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthGenerated
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthGenerated        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowGenerated          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupGenerated = fmt.Errorf("proto: unexpected end of group")
)
