// +build !ignore_autogenerated

// Copyright 2020 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	metrics "github.com/vmware-tanzu/antrea/pkg/apis/metrics"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ClusterNetworkPolicyMetric)(nil), (*metrics.ClusterNetworkPolicyMetric)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterNetworkPolicyMetric_To_metrics_ClusterNetworkPolicyMetric(a.(*ClusterNetworkPolicyMetric), b.(*metrics.ClusterNetworkPolicyMetric), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*metrics.ClusterNetworkPolicyMetric)(nil), (*ClusterNetworkPolicyMetric)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_metrics_ClusterNetworkPolicyMetric_To_v1alpha1_ClusterNetworkPolicyMetric(a.(*metrics.ClusterNetworkPolicyMetric), b.(*ClusterNetworkPolicyMetric), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*ClusterNetworkPolicyMetricList)(nil), (*metrics.ClusterNetworkPolicyMetricList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ClusterNetworkPolicyMetricList_To_metrics_ClusterNetworkPolicyMetricList(a.(*ClusterNetworkPolicyMetricList), b.(*metrics.ClusterNetworkPolicyMetricList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*metrics.ClusterNetworkPolicyMetricList)(nil), (*ClusterNetworkPolicyMetricList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_metrics_ClusterNetworkPolicyMetricList_To_v1alpha1_ClusterNetworkPolicyMetricList(a.(*metrics.ClusterNetworkPolicyMetricList), b.(*ClusterNetworkPolicyMetricList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*K8sNetworkPolicyMetric)(nil), (*metrics.K8sNetworkPolicyMetric)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_K8sNetworkPolicyMetric_To_metrics_K8sNetworkPolicyMetric(a.(*K8sNetworkPolicyMetric), b.(*metrics.K8sNetworkPolicyMetric), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*metrics.K8sNetworkPolicyMetric)(nil), (*K8sNetworkPolicyMetric)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_metrics_K8sNetworkPolicyMetric_To_v1alpha1_K8sNetworkPolicyMetric(a.(*metrics.K8sNetworkPolicyMetric), b.(*K8sNetworkPolicyMetric), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*K8sNetworkPolicyMetricList)(nil), (*metrics.K8sNetworkPolicyMetricList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_K8sNetworkPolicyMetricList_To_metrics_K8sNetworkPolicyMetricList(a.(*K8sNetworkPolicyMetricList), b.(*metrics.K8sNetworkPolicyMetricList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*metrics.K8sNetworkPolicyMetricList)(nil), (*K8sNetworkPolicyMetricList)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_metrics_K8sNetworkPolicyMetricList_To_v1alpha1_K8sNetworkPolicyMetricList(a.(*metrics.K8sNetworkPolicyMetricList), b.(*K8sNetworkPolicyMetricList), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*NetworkPolicyStats)(nil), (*metrics.NetworkPolicyStats)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_NetworkPolicyStats_To_metrics_NetworkPolicyStats(a.(*NetworkPolicyStats), b.(*metrics.NetworkPolicyStats), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*metrics.NetworkPolicyStats)(nil), (*NetworkPolicyStats)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_metrics_NetworkPolicyStats_To_v1alpha1_NetworkPolicyStats(a.(*metrics.NetworkPolicyStats), b.(*NetworkPolicyStats), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ClusterNetworkPolicyMetric_To_metrics_ClusterNetworkPolicyMetric(in *ClusterNetworkPolicyMetric, out *metrics.ClusterNetworkPolicyMetric, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.StartTime = in.StartTime
	if err := Convert_v1alpha1_NetworkPolicyStats_To_metrics_NetworkPolicyStats(&in.Stats, &out.Stats, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_ClusterNetworkPolicyMetric_To_metrics_ClusterNetworkPolicyMetric is an autogenerated conversion function.
func Convert_v1alpha1_ClusterNetworkPolicyMetric_To_metrics_ClusterNetworkPolicyMetric(in *ClusterNetworkPolicyMetric, out *metrics.ClusterNetworkPolicyMetric, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterNetworkPolicyMetric_To_metrics_ClusterNetworkPolicyMetric(in, out, s)
}

func autoConvert_metrics_ClusterNetworkPolicyMetric_To_v1alpha1_ClusterNetworkPolicyMetric(in *metrics.ClusterNetworkPolicyMetric, out *ClusterNetworkPolicyMetric, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.StartTime = in.StartTime
	if err := Convert_metrics_NetworkPolicyStats_To_v1alpha1_NetworkPolicyStats(&in.Stats, &out.Stats, s); err != nil {
		return err
	}
	return nil
}

// Convert_metrics_ClusterNetworkPolicyMetric_To_v1alpha1_ClusterNetworkPolicyMetric is an autogenerated conversion function.
func Convert_metrics_ClusterNetworkPolicyMetric_To_v1alpha1_ClusterNetworkPolicyMetric(in *metrics.ClusterNetworkPolicyMetric, out *ClusterNetworkPolicyMetric, s conversion.Scope) error {
	return autoConvert_metrics_ClusterNetworkPolicyMetric_To_v1alpha1_ClusterNetworkPolicyMetric(in, out, s)
}

func autoConvert_v1alpha1_ClusterNetworkPolicyMetricList_To_metrics_ClusterNetworkPolicyMetricList(in *ClusterNetworkPolicyMetricList, out *metrics.ClusterNetworkPolicyMetricList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]metrics.ClusterNetworkPolicyMetric)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_ClusterNetworkPolicyMetricList_To_metrics_ClusterNetworkPolicyMetricList is an autogenerated conversion function.
func Convert_v1alpha1_ClusterNetworkPolicyMetricList_To_metrics_ClusterNetworkPolicyMetricList(in *ClusterNetworkPolicyMetricList, out *metrics.ClusterNetworkPolicyMetricList, s conversion.Scope) error {
	return autoConvert_v1alpha1_ClusterNetworkPolicyMetricList_To_metrics_ClusterNetworkPolicyMetricList(in, out, s)
}

func autoConvert_metrics_ClusterNetworkPolicyMetricList_To_v1alpha1_ClusterNetworkPolicyMetricList(in *metrics.ClusterNetworkPolicyMetricList, out *ClusterNetworkPolicyMetricList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]ClusterNetworkPolicyMetric)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_metrics_ClusterNetworkPolicyMetricList_To_v1alpha1_ClusterNetworkPolicyMetricList is an autogenerated conversion function.
func Convert_metrics_ClusterNetworkPolicyMetricList_To_v1alpha1_ClusterNetworkPolicyMetricList(in *metrics.ClusterNetworkPolicyMetricList, out *ClusterNetworkPolicyMetricList, s conversion.Scope) error {
	return autoConvert_metrics_ClusterNetworkPolicyMetricList_To_v1alpha1_ClusterNetworkPolicyMetricList(in, out, s)
}

func autoConvert_v1alpha1_K8sNetworkPolicyMetric_To_metrics_K8sNetworkPolicyMetric(in *K8sNetworkPolicyMetric, out *metrics.K8sNetworkPolicyMetric, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.StartTime = in.StartTime
	if err := Convert_v1alpha1_NetworkPolicyStats_To_metrics_NetworkPolicyStats(&in.Stats, &out.Stats, s); err != nil {
		return err
	}
	return nil
}

// Convert_v1alpha1_K8sNetworkPolicyMetric_To_metrics_K8sNetworkPolicyMetric is an autogenerated conversion function.
func Convert_v1alpha1_K8sNetworkPolicyMetric_To_metrics_K8sNetworkPolicyMetric(in *K8sNetworkPolicyMetric, out *metrics.K8sNetworkPolicyMetric, s conversion.Scope) error {
	return autoConvert_v1alpha1_K8sNetworkPolicyMetric_To_metrics_K8sNetworkPolicyMetric(in, out, s)
}

func autoConvert_metrics_K8sNetworkPolicyMetric_To_v1alpha1_K8sNetworkPolicyMetric(in *metrics.K8sNetworkPolicyMetric, out *K8sNetworkPolicyMetric, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.StartTime = in.StartTime
	if err := Convert_metrics_NetworkPolicyStats_To_v1alpha1_NetworkPolicyStats(&in.Stats, &out.Stats, s); err != nil {
		return err
	}
	return nil
}

// Convert_metrics_K8sNetworkPolicyMetric_To_v1alpha1_K8sNetworkPolicyMetric is an autogenerated conversion function.
func Convert_metrics_K8sNetworkPolicyMetric_To_v1alpha1_K8sNetworkPolicyMetric(in *metrics.K8sNetworkPolicyMetric, out *K8sNetworkPolicyMetric, s conversion.Scope) error {
	return autoConvert_metrics_K8sNetworkPolicyMetric_To_v1alpha1_K8sNetworkPolicyMetric(in, out, s)
}

func autoConvert_v1alpha1_K8sNetworkPolicyMetricList_To_metrics_K8sNetworkPolicyMetricList(in *K8sNetworkPolicyMetricList, out *metrics.K8sNetworkPolicyMetricList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]metrics.K8sNetworkPolicyMetric)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_v1alpha1_K8sNetworkPolicyMetricList_To_metrics_K8sNetworkPolicyMetricList is an autogenerated conversion function.
func Convert_v1alpha1_K8sNetworkPolicyMetricList_To_metrics_K8sNetworkPolicyMetricList(in *K8sNetworkPolicyMetricList, out *metrics.K8sNetworkPolicyMetricList, s conversion.Scope) error {
	return autoConvert_v1alpha1_K8sNetworkPolicyMetricList_To_metrics_K8sNetworkPolicyMetricList(in, out, s)
}

func autoConvert_metrics_K8sNetworkPolicyMetricList_To_v1alpha1_K8sNetworkPolicyMetricList(in *metrics.K8sNetworkPolicyMetricList, out *K8sNetworkPolicyMetricList, s conversion.Scope) error {
	out.ListMeta = in.ListMeta
	out.Items = *(*[]K8sNetworkPolicyMetric)(unsafe.Pointer(&in.Items))
	return nil
}

// Convert_metrics_K8sNetworkPolicyMetricList_To_v1alpha1_K8sNetworkPolicyMetricList is an autogenerated conversion function.
func Convert_metrics_K8sNetworkPolicyMetricList_To_v1alpha1_K8sNetworkPolicyMetricList(in *metrics.K8sNetworkPolicyMetricList, out *K8sNetworkPolicyMetricList, s conversion.Scope) error {
	return autoConvert_metrics_K8sNetworkPolicyMetricList_To_v1alpha1_K8sNetworkPolicyMetricList(in, out, s)
}

func autoConvert_v1alpha1_NetworkPolicyStats_To_metrics_NetworkPolicyStats(in *NetworkPolicyStats, out *metrics.NetworkPolicyStats, s conversion.Scope) error {
	out.Packets = in.Packets
	out.Bytes = in.Bytes
	out.Sessions = in.Sessions
	return nil
}

// Convert_v1alpha1_NetworkPolicyStats_To_metrics_NetworkPolicyStats is an autogenerated conversion function.
func Convert_v1alpha1_NetworkPolicyStats_To_metrics_NetworkPolicyStats(in *NetworkPolicyStats, out *metrics.NetworkPolicyStats, s conversion.Scope) error {
	return autoConvert_v1alpha1_NetworkPolicyStats_To_metrics_NetworkPolicyStats(in, out, s)
}

func autoConvert_metrics_NetworkPolicyStats_To_v1alpha1_NetworkPolicyStats(in *metrics.NetworkPolicyStats, out *NetworkPolicyStats, s conversion.Scope) error {
	out.Packets = in.Packets
	out.Bytes = in.Bytes
	out.Sessions = in.Sessions
	return nil
}

// Convert_metrics_NetworkPolicyStats_To_v1alpha1_NetworkPolicyStats is an autogenerated conversion function.
func Convert_metrics_NetworkPolicyStats_To_v1alpha1_NetworkPolicyStats(in *metrics.NetworkPolicyStats, out *NetworkPolicyStats, s conversion.Scope) error {
	return autoConvert_metrics_NetworkPolicyStats_To_v1alpha1_NetworkPolicyStats(in, out, s)
}
