apiVersion: crd.antrea.io/v1alpha2
kind: Egress
metadata:
  name: egress-dev2
spec:
  appliedTo:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: dev2
  externalIPPool: external-ip-pool
