apiVersion: crd.antrea.io/v1alpha2
kind: ExternalIPPool
metadata:
  name: external-ip-pool
spec:
  ipRanges:
    - start: 172.16.10.11
      end: 172.16.10.20
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
---
apiVersion: crd.antrea.io/v1alpha2
kind: Egress
metadata:
  name: egress-dev1
spec:
  appliedTo:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: dev1
  externalIPPool: external-ip-pool
