// Copyright 2022 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "antrea.io/antrea/pkg/apis/crd/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// L7NetworkPolicyLister helps list L7NetworkPolicies.
// All objects returned here must be treated as read-only.
type L7NetworkPolicyLister interface {
	// List lists all L7NetworkPolicies in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.L7NetworkPolicy, err error)
	// L7NetworkPolicies returns an object that can list and get L7NetworkPolicies.
	L7NetworkPolicies(namespace string) L7NetworkPolicyNamespaceLister
	L7NetworkPolicyListerExpansion
}

// l7NetworkPolicyLister implements the L7NetworkPolicyLister interface.
type l7NetworkPolicyLister struct {
	indexer cache.Indexer
}

// NewL7NetworkPolicyLister returns a new L7NetworkPolicyLister.
func NewL7NetworkPolicyLister(indexer cache.Indexer) L7NetworkPolicyLister {
	return &l7NetworkPolicyLister{indexer: indexer}
}

// List lists all L7NetworkPolicies in the indexer.
func (s *l7NetworkPolicyLister) List(selector labels.Selector) (ret []*v1alpha1.L7NetworkPolicy, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.L7NetworkPolicy))
	})
	return ret, err
}

// L7NetworkPolicies returns an object that can list and get L7NetworkPolicies.
func (s *l7NetworkPolicyLister) L7NetworkPolicies(namespace string) L7NetworkPolicyNamespaceLister {
	return l7NetworkPolicyNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// L7NetworkPolicyNamespaceLister helps list and get L7NetworkPolicies.
// All objects returned here must be treated as read-only.
type L7NetworkPolicyNamespaceLister interface {
	// List lists all L7NetworkPolicies in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.L7NetworkPolicy, err error)
	// Get retrieves the L7NetworkPolicy from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.L7NetworkPolicy, error)
	L7NetworkPolicyNamespaceListerExpansion
}

// l7NetworkPolicyNamespaceLister implements the L7NetworkPolicyNamespaceLister
// interface.
type l7NetworkPolicyNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all L7NetworkPolicies in the indexer for a given namespace.
func (s l7NetworkPolicyNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.L7NetworkPolicy, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.L7NetworkPolicy))
	})
	return ret, err
}

// Get retrieves the L7NetworkPolicy from the indexer for a given namespace and name.
func (s l7NetworkPolicyNamespaceLister) Get(name string) (*v1alpha1.L7NetworkPolicy, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("l7networkpolicy"), name)
	}
	return obj.(*v1alpha1.L7NetworkPolicy), nil
}
