// Copyright 2020 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/vmware-tanzu/antrea/pkg/apis/crd/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// TierEntitlementBindingLister helps list TierEntitlementBindings.
type TierEntitlementBindingLister interface {
	// List lists all TierEntitlementBindings in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.TierEntitlementBinding, err error)
	// Get retrieves the TierEntitlementBinding from the index for a given name.
	Get(name string) (*v1alpha1.TierEntitlementBinding, error)
	TierEntitlementBindingListerExpansion
}

// tierEntitlementBindingLister implements the TierEntitlementBindingLister interface.
type tierEntitlementBindingLister struct {
	indexer cache.Indexer
}

// NewTierEntitlementBindingLister returns a new TierEntitlementBindingLister.
func NewTierEntitlementBindingLister(indexer cache.Indexer) TierEntitlementBindingLister {
	return &tierEntitlementBindingLister{indexer: indexer}
}

// List lists all TierEntitlementBindings in the indexer.
func (s *tierEntitlementBindingLister) List(selector labels.Selector) (ret []*v1alpha1.TierEntitlementBinding, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.TierEntitlementBinding))
	})
	return ret, err
}

// Get retrieves the TierEntitlementBinding from the index for a given name.
func (s *tierEntitlementBindingLister) Get(name string) (*v1alpha1.TierEntitlementBinding, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("tierentitlementbinding"), name)
	}
	return obj.(*v1alpha1.TierEntitlementBinding), nil
}
