// Copyright 2021 Antrea Authors
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "antrea.io/antrea/pkg/apis/crd/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// TrafficControlConfigurationLister helps list TrafficControlConfigurations.
// All objects returned here must be treated as read-only.
type TrafficControlConfigurationLister interface {
	// List lists all TrafficControlConfigurations in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.TrafficControlConfiguration, err error)
	// Get retrieves the TrafficControlConfiguration from the index for a given name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.TrafficControlConfiguration, error)
	TrafficControlConfigurationListerExpansion
}

// trafficControlConfigurationLister implements the TrafficControlConfigurationLister interface.
type trafficControlConfigurationLister struct {
	indexer cache.Indexer
}

// NewTrafficControlConfigurationLister returns a new TrafficControlConfigurationLister.
func NewTrafficControlConfigurationLister(indexer cache.Indexer) TrafficControlConfigurationLister {
	return &trafficControlConfigurationLister{indexer: indexer}
}

// List lists all TrafficControlConfigurations in the indexer.
func (s *trafficControlConfigurationLister) List(selector labels.Selector) (ret []*v1alpha1.TrafficControlConfiguration, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.TrafficControlConfiguration))
	})
	return ret, err
}

// Get retrieves the TrafficControlConfiguration from the index for a given name.
func (s *trafficControlConfigurationLister) Get(name string) (*v1alpha1.TrafficControlConfiguration, error) {
	obj, exists, err := s.indexer.GetByKey(name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("trafficcontrolconfiguration"), name)
	}
	return obj.(*v1alpha1.TrafficControlConfiguration), nil
}
