# Anyone with write permissions to the antrea-io/antrea Github repository can
# trigger this workflow manually, but please check with a maintainer first. The
# workflow will build and push the antrea/ethtool image, with multi-platform
# support.
name: Manually kind

on:
  workflow_dispatch:
    # It is unlikely that anyone will need to use non-default values for these inputs.
    inputs:
      antrea-version:
        description: The Git ref to use when checking-out the Antrea repository
        required: false
      kind-version:
        description: Kind version
        required: false
        default: v0.19.0
      k8s-version:
        description: K8s version, Kind's default K8s version will be used if empty.
        required: false

jobs:
#  build-antrea-image:
#    name: Build Antrea image to be used for Kind e2e tests
#    needs: check-changes
#    if: ${{ needs.check-changes.outputs.has_changes == 'yes' }}
#    runs-on: [ubuntu-latest]
#    steps:
#      - uses: actions/checkout@v3
#      - name: Build Antrea Docker image with code coverage support
#        run: |
#          ./hack/build-antrea-linux-all.sh --pull
#      - name: Save Antrea image to tarball
#        run:  docker save -o antrea-ubuntu.tar antrea/antrea-ubuntu:latest
#      - name: Upload Antrea image for subsequent jobs
#        uses: actions/upload-artifact@v3
#        with:
#          name: antrea-ubuntu
#          path: antrea-ubuntu.tar
#          retention-days: 1 # minimum value, in case artifact deletion by 'artifact-cleanup' job fails

  test-e2e:
    name: E2e tests on a Kind cluster on Linux
    needs: [build-antrea-image]
    runs-on: [ubuntu-latest]
    steps:
      - name: Free disk space
        # https://github.com/actions/virtual-environments/issues/709
        run: |
          sudo apt-get clean
          df -h
#      - uses: actions/checkout@v3
#      - uses: actions/setup-go@v4
#        with:
#          go-version-file: 'go.mod'
#      - name: Download Antrea image from previous job
#        uses: actions/download-artifact@v3
#        with:
#          name: antrea-ubuntu
#      - name: Load Antrea image
#        run: |
#          docker load -i antrea-ubuntu.tar
      - name: Install Kind
        run: |
          curl -Lo ./kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-$(uname)-amd64
          chmod +x ./kind
          sudo mv kind /usr/local/bin
      - name: Create K8s cluster
        run: |
          ./ci/kind/kind-setup.sh \
            --encap-mode encap \
            --k8s-version "${{ github.event.inputs.k8s-version }}"
      - name: Install Antrea
        run: |
          helm repo add antrea https://charts.antrea.io
          helm repo update
          helm install --namespace kube-system antrea antrea/antrea --version "${{ github.event.inputs.antrea-version }}"
          kubectl rollout status -n kube-system ds/antrea-agent --timeout=5m
      - name: Run e2e tests
        run: |
          ./ci/run-k8s-e2e-tests.sh --e2e-conformance --e2e-focus "abc"
#      - name: Tar log files
#        if: ${{ failure() }}
#        run: tar -czf log.tar.gz log
#      - name: Upload test log
#        uses: actions/upload-artifact@v3
#        if: ${{ failure() }}
#        with:
#          name: e2e-kind-encap.tar.gz
#          path: log.tar.gz
#          retention-days: 30

  # Runs after all other jobs in the workflow succeed and deletes Antrea Docker images uploaded as temporary
  # artifacts. It uses a third-party, MIT-licensed action (geekyeggo/delete-artifact). While Github
  # exposes an API for deleting artifacts, they do not support an official delete-artifact action
  # yet.
#  artifact-cleanup:
#    name: Delete uploaded images
#    needs:
#      - build-antrea-image
#      - test-e2e-encap
#    runs-on: [ubuntu-latest]
#    steps:
#      - name: Delete antrea-ubuntu
#        if: ${{ needs.build-antrea-image.result == 'success' }}
#        uses: geekyeggo/delete-artifact@v2
#        with:
#          name: antrea-ubuntu
