name: Pull Request Labels
on:
  pull_request:
    types: [opened, labeled, unlabeled, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v4
        with:
          mode: minimum
          count: 1
          labels: "action/backport, action/release-note, action/none"
          add_comment: true
